### ISSUE TITLE
AnnotationTextNodes should be replaced

### ISSUE THREAD

**Issue by ungi** [SlicerIGT/OpenIGTLinkRemote#20]
Currently the commands and acknowledgments are stored in vtkMRMLAnnotationTextNodes. These types of nodes will be removed from Slicer. Another node type should be used that supports string messages.

**Comment by lassoan** [comment]
Fixed in Slicer trunk rev 23992:

ENH: Updated OpenIGTLinkIF
Enhancements for better OpenIGTLink string command support
https://github.com/openigtlink/OpenIGTLinkIF/pull/48
